[versions]
# plugins
changelog = "2.2.0"
intelliJPlatform = "2.0.0-rc1"
kotlin = "2.0.20-Beta2"

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
